version: '3'

services:
  user_services:
    build:
      context: ./user_services
      dockerfile: Dockerfile
    networks:
      - microservices
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - userRedis
      
  message_services:
    build:
      context: ./message_services
      dockerfile: Dockerfile
    networks:
      - microservices
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - messageRedis

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - microservices
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user_services
      - message_services
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - microservices

  messageRedis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - microservices
    
  userRedis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  mysql_data:
    driver: local